### ISSUE TITLE
pwp logs on every pages

### ISSUE THREAD

**Issue by dcfvg** [byte-foundry/prototypo-web-preview#1]
Hi, 
I've been installing prototypo web preview yesterday after you newsletter. Since then I get this message in my console on every pages I load ( a script seem to be missing )…

```
GET https://app.prototypo.io/dll/libs.dll.js  iframe.html:13 
/prototypo-canvas/src/worker.js web-import.js:64136
```

bests

**Comment by YoruNoHikage** [comment]
Since the 2.0.0 rewrite, it shouldn't be a problem anymore.
